---
title: "Project: Human gut- derived commensal induces tolerance to gluten in humanized mice"
author: "Rahul Bodkhe"
date: "May, 21 2019"
output: html_document
---

```{r}
library(ggplot2)
library(ape)
library(plyr)
library(vegan)
library(Biostrings)
library(RColorBrewer)
library(reshape2)
library(scales)
library(data.table)
library(microbiome)
library(dplyr)
library(phyloseq)

```
##GFD p_histicola
```{r}
rm(list = ls())
pseq1 <- readRDS("Gluten_free_Diet_qiime_Green_gene_finalinjected_as_pm2.rds")
pseq3 <- subset_samples(pseq1, Treatment!= "Media_A.Muc")
pseq4 <- subset_samples(pseq3, Treatment!= "Media_F.praus")
pseq7 <- subset_samples(pseq4, Treatment != c("F.prausnitzii"))
pseq88 <- subset_samples(pseq7, Sample_names != "1715a") 
pseq9 <- subset_samples(pseq88, Sample_names != "1716b")
pseq8 <- subset_samples(pseq9, Sample_names != "1705b")
pseq9 <- subset_samples(pseq8, Sample_names != "1709b") 
pseq10 <- subset_samples(pseq9, Sample_names != "1731b")
pseq11 <- subset_samples(pseq10, Sample_names != "1732b")
pseq69 <- subset_samples(pseq11, Sample_names != "1733b")
pseq70 <- subset_samples(pseq69, Sample_names != "1704b")
pseq72 <- subset_samples(pseq70, Sample_names != "1706b")
pseq73 <- subset_samples(pseq72, Sample_names != "1707b")
pseq74 <- subset_samples(pseq73, Sample_names != "1730b")
pseq75 <- subset_samples(pseq74, Sample_names != "1729b")
pseq11 <- subset_samples(pseq75, Treatment != c("A.Muciniphila"))
pseq12 <- subset_samples(pseq11, Treatment != c("P.histicola"))
pseq13 <- subset_samples(pseq12, Treatment != c("Control")) 
pseq14 <- subset_samples(pseq13, Treatment != c(".Naïve"))
pseq15 <- subset_samples(pseq14, Treatment != c(".PTD_Gliadin_Injected")) 
pseq15
pseq <- prune_taxa(taxa_sums(pseq15)>1, pseq15)
sample_data(pseq)
```
```{r}
data.phylum <- pseq %>%
    tax_glom(taxrank = "Phylum") %>% 
    transform_sample_counts(function(x){x/sum(x)}) %>%
 psmelt() %>% 
filter(Abundance > 0.005) %>%
    arrange(Phylum)

```
```{r}
my_colors <- c( "darkorange1", "darkblue",  "#556B2F",  "#800000")
p <- ggplot(data.phylum, aes(x = Treatment, y = Abundance, fill = Phylum)) +
    geom_bar(stat = "identity",position="fill") + # to equal 1
    theme_classic() +
    scale_fill_manual(values = my_colors) +
    theme(text = element_text(size=10),axis.text.y = element_text(hjust=1)) +
    scale_x_discrete(drop=TRUE) +
    theme(axis.title.x = element_blank()) + # Remove x axis title
    guides(fill = guide_legend( keywidth = 1, keyheight = 1)) +
    ylab("Distribution of OTUs at phylum level in P melaninogenica mice") 
p + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) + facet_grid(cols =  vars(Time_of_sampling))

ggsave("GFD_Distribution of Bacterial taxa at phylum level in in P melaninogenica mice.tiff", height = 4, width = 5)
```
```{r}
pseqw <- subset_taxa(pseq, Family!= "f__")
pseqv <- subset_taxa(pseqw, Family!= "f__mitochondria")
data.family <- pseqv %>%
    tax_glom(taxrank = "Family") %>% 
    transform_sample_counts(function(x){x/sum(x)}) %>%
 psmelt() %>% 
  filter(Abundance > 0.005) %>%
      arrange(Family)
```

```{r}
my_colors <- c( "darkblue",
 "#556B2F",  
"#800000",
"#599861",
 "#4B0082",
"#fb9a99",
 "#800080", 
 "#FF00FF",
 "dodgerblue3",
  "darkgoldenrod1",
 "#808000",
 "darkseagreen",
 "darkorchid",
 "darkolivegreen1",
 "brown1",
"#330019",
"#D1A33D",
 "#5F7FC7")
p <- ggplot(data.family, aes(x = Treatment, y = Abundance, fill = Family)) +
    geom_bar(stat = "identity",position="fill") + # to equal 1
    theme_classic() +
    scale_fill_manual(values = my_colors) +
    theme(text = element_text(size=10),axis.text.y = element_text(hjust=1)) +
    scale_x_discrete(drop=TRUE) +
    theme(axis.title.x = element_blank()) + # Remove x axis title
    guides(fill = guide_legend( keywidth = 1, keyheight = 1)) +
    ylab("Distribution of OTUs at Family level in P melaninogenica mice") 
p + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) + facet_grid(cols =  vars(Time_of_sampling))

ggsave("GFD_family P melaninogenica mice_s247.tiff", height = 4, width = 5)
ggsave("GFD_family P melaninogenica mice_s247.pdf", height = 4, width = 5)


```
```{r}

pseqw <- subset_taxa(pseq, Family!= "f__")
pseqv <- subset_taxa(pseqw, Family!= "f__S24-7")
data.family <- pseqv %>%
    tax_glom(taxrank = "Family") %>% 
    transform_sample_counts(function(x){x/sum(x)}) %>%
 psmelt() %>% 
  filter(Abundance > 0.005) %>%
      arrange(Family)

```

```{r}
my_colors <- c(   "darkblue",

"#800000",

  "darkorange1",
 "#0000FF",
 "#4B0082",
"#c51b7d",
"#fb9a99",
 "#800080", 
"#599861",
 "#FF00FF",
 "dodgerblue3",
  "darkgoldenrod1",
 "#808000",
 "darkseagreen",
 "darkorchid",
 "darkolivegreen1",
 "brown1",
"#000000",
 "#5F7FC7",
  "darkgoldenrod1",
 "#808000",
 "darkseagreen",
 "darkorchid",
 "darkolivegreen1",
 "brown1",
"#000000",
 "#5F7FC7")

p <- ggplot(data.family, aes(x = Treatment, y = Abundance, fill = Family)) +
    geom_bar(stat = "identity",position="fill") + # to equal 1
    theme_classic() +
    scale_fill_manual(values = my_colors) +
    theme(text = element_text(size=10),axis.text.y = element_text(hjust=1)) +
    scale_x_discrete(drop=TRUE) +
    theme(axis.title.x = element_blank()) + # Remove x axis title
    guides(fill = guide_legend( keywidth = 1, keyheight = 1)) +
    ylab("Distribution of OTUs at Family level in P melaninogenica mice") 
p + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) + facet_grid(cols =  vars(Time_of_sampling))

ggsave("Distribution of bacterial taxa at Family level in P melaninogenica mice.tiff", height = 4, width = 5)
ggsave("Distribution of bacterial taxa at Family level in P melaninogenica mice.pdf", height = 4, width = 5)

```
```{r}
pseqc <- subset_taxa(pseq, Genus!= "g__")
data.genus <- pseqc %>%
    tax_glom(taxrank = "Genus") %>% 
    transform_sample_counts(function(x){x/sum(x)}) %>%
 psmelt() %>% 
    filter(Abundance > 0.005) %>%

    arrange(Genus)
```

```{r}
my_colors <- c( "darkblue",
 "#556B2F",
 "#0000FF",
"#008080",
 "#800000",
 "#4B0082",
 "darkolivegreen1",
 "#fb9a99",
 "#FF00FF",
 "dodgerblue3",
 "#808000",
 "#800080", 
  "darkgoldenrod1",
 "darkseagreen",
"#000000",
 "#c51b7d",
 "#5F7FC7",
 "darkorchid",
"steelblue",
"brown1",
"#D1A33D",
"#666600")
p <- ggplot(data.genus, aes(x = Treatment, y = Abundance, fill = Genus)) +
    geom_bar(stat = "identity",position="fill") + # to equal 1
    theme_classic() +
    scale_fill_manual(values = my_colors) +
    theme(text = element_text(size=10),axis.text.y = element_text(hjust=1)) +
    scale_x_discrete(drop=TRUE) +
    theme(axis.title.x = element_blank()) + # Remove x axis title
    guides(fill = guide_legend( keywidth = 1, keyheight = 1)) +
    ylab("Distribution of OTUs at Genus level in P melaninogenica mice") 
p + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) + facet_grid(cols =  vars(Time_of_sampling)) +  guides(col = guide_legend(ncol = 22))


ggsave("Distribution of bacterial taxa at genus level in P melaninogenica mice.tiff", height = 4, width = 7)
ggsave("Distribution of bacterial taxa at genus level in P melaninogenica mice.pdf", height = 4, width = 7)
```