---
title: "Fecal/Salivary microbiome stack plot"
author: "Rahul Bodkhe"
date: "May, 21 2019"
output: html_document
---

```{r}
library(ggplot2)
library(ape)
library(plyr)
library(vegan)
library(Biostrings)
library(RColorBrewer)
library(reshape2)
library(scales)
library(data.table)
library(microbiome)
library(dplyr)
library(phyloseq)

```
##GFD p_histicola
```{r}
	rm(list = ls())
pseq2 <- readRDS("Gluten_free_Diet_qiime_Green_gene_finalinjected_as_pm2.rds")
pseq3 <- subset_samples(pseq2, Treatment!= "Media_A.Muc")
pseq4 <- subset_samples(pseq3, Treatment!= "Media_F.praus")
pseq6 <- subset_samples(pseq4, Treatment != c("Control"))
pseq7 <- subset_samples(pseq6, Treatment != c("F.prausnitzii"))
pseq8 <- subset_samples(pseq7, Treatment != c("A.Muciniphila"))
pseq9 <- subset_samples(pseq8, Treatment != c(".Naïve"))
pseq10 <- subset_samples(pseq9, Treatment != c("P.Melaninogenica"))
pseq11 <- subset_samples(pseq10, Treatment != c(".PTD_Gliadin_Injected"))
pseq11
pseq <- prune_taxa(taxa_sums(pseq11)>1, pseq11)
sample_data(pseq)
```
```{r}
data.phylum <- pseq %>%
    tax_glom(taxrank = "Phylum") %>% 
    transform_sample_counts(function(x){x/sum(x)}) %>%
 psmelt() %>% 
filter(Abundance > 0.005) %>%
    arrange(Phylum)

```
```{r}
my_colors<- c( "darkorange1", "darkblue",  "#556B2F",  "#800000")
p <- ggplot(data.phylum, aes(x = Treatment, y = Abundance, fill = Phylum)) +
    geom_bar(stat = "identity",position="fill") + # to equal 1
    theme_classic() +
    scale_fill_manual(values = my_colors) +
    theme(text = element_text(size=10),axis.text.y = element_text(hjust=1)) +
    scale_x_discrete(drop=TRUE) +
    theme(axis.title.x = element_blank()) + # Remove x axis title
    guides(fill = guide_legend( keywidth = 1, keyheight = 1)) +
    ylab("Distribution of OTUs at phylum level in P_histicola mice") 
p + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) + facet_grid(cols =  vars(Time_of_sampling))

ggsave("GFD_Distribution of Bacterial taxa at phylum level in in P_histicola mice.tiff", height = 4, width = 5)
```
```{r}
pseqw <- subset_taxa(pseq, Family!= "f__")
pseqv <- subset_taxa(pseqw, Family!= "f__mitochondria")
data.family <- pseqv %>%
    tax_glom(taxrank = "Family") %>% 
    transform_sample_counts(function(x){x/sum(x)}) %>%
 psmelt() %>% 
  filter(Abundance > 0.005) %>%
      arrange(Family)
```

```{r}
my_colors <- c(  "darkblue",
"#800000",
 "#599861",
 "#4B0082",
"#fb9a99",
 "#FF00FF",
 "dodgerblue3",
  "darkgoldenrod1",
 "#808000",
 "darkseagreen",
 "darkolivegreen1",
 "brown1",
"#330019",
"#D1A33D",
 "#5F7FC7")
p <- ggplot(data.family, aes(x = Treatment, y = Abundance, fill = Family)) +
    geom_bar(stat = "identity",position="fill") + # to equal 1
    theme_classic() +
    scale_fill_manual(values = my_colors) +
    theme(text = element_text(size=10),axis.text.y = element_text(hjust=1)) +
    scale_x_discrete(drop=TRUE) +
    theme(axis.title.x = element_blank()) + # Remove x axis title
    guides(fill = guide_legend( keywidth = 1, keyheight = 1)) +
    ylab("Distribution of OTUs at Family level in P_histicola mice") 
p + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) + facet_grid(cols =  vars(Time_of_sampling))

ggsave("GFD_family level in  P_histicola mice with s247.tiff", height = 4, width = 5)

ggsave("GFD_family level in  P_histicola mice with s247.pdf", height = 4, width = 5)
```
```{r}

pseqw <- subset_taxa(pseq, Family!= "f__")
pseqv <- subset_taxa(pseqw, Family!= "f__S24-7")
data.family <- pseqv %>%
    tax_glom(taxrank = "Family") %>% 
    transform_sample_counts(function(x){x/sum(x)}) %>%
 psmelt() %>% 
  filter(Abundance > 0.005) %>%
      arrange(Family)

```

```{r}
my_colors <- c( "#8A7C64",
 "darkblue",

"#800000",


 "#0000FF",
 "#4B0082",
"#c51b7d",
"#fb9a99",
 "#FF00FF",
"#599861",
 "dodgerblue3",
  "darkgoldenrod1",
 "#808000",
 "darkseagreen",
 "darkolivegreen1",
 "brown1",
"#000000",
 "#5F7FC7")

p <- ggplot(data.family, aes(x = Treatment, y = Abundance, fill = Family)) +
    geom_bar(stat = "identity",position="fill") + # to equal 1
    theme_classic() +
    scale_fill_manual(values = my_colors) +
    theme(text = element_text(size=10),axis.text.y = element_text(hjust=1)) +
    scale_x_discrete(drop=TRUE) +
    theme(axis.title.x = element_blank()) + # Remove x axis title
    guides(fill = guide_legend( keywidth = 1, keyheight = 1)) +
    ylab("Distribution of OTUs at Family level in P_histicola mice") 
p + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) + facet_grid(cols =  vars(Time_of_sampling))

ggsave("Distribution of bacterial taxa at Family level in P_histicola P_histicola mice.tiff", height = 4, width = 5)
ggsave("Distribution of bacterial taxa at Family level in P_histicola P_histicola mice.pdf", height = 4, width = 5)

```
```{r}
pseqc <- subset_taxa(pseq, Genus!= "g__")
data.genus <- pseqc %>%
    tax_glom(taxrank = "Genus") %>% 
    transform_sample_counts(function(x){x/sum(x)}) %>%
 psmelt() %>% 
    filter(Abundance > 0.005) %>%

    arrange(Genus)
```

```{r}
my_colors <- c( "darkblue",
 "#556B2F",
"#008080",
    "darkorange1",
 "#800000",
 "darkolivegreen1",
 "#fb9a99",
 "#FF00FF",
 "dodgerblue3",
 "#808000",
  "darkgoldenrod1",
 "darkseagreen",
"#000000",
 "#c51b7d",
 "#5F7FC7",
"brown1",
"#666600")
p <- ggplot(data.genus, aes(x = Treatment, y = Abundance, fill = Genus)) +
    geom_bar(stat = "identity",position="fill") + # to equal 1
    theme_classic() +
    scale_fill_manual(values = my_colors) +
    theme(text = element_text(size=10),axis.text.y = element_text(hjust=1)) +
    scale_x_discrete(drop=TRUE) +
    theme(axis.title.x = element_blank()) + # Remove x axis title
    guides(fill = guide_legend( keywidth = 1, keyheight = 1)) +
    ylab("Distribution of OTUs at Genus level in P_histicola mice") 
p + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) + facet_grid(cols =  vars(Time_of_sampling))

ggsave("Distribution of bacterial taxa at genus level in P_histicola mice.tiff", height = 4, width = 5)
ggsave("Distribution of bacterial taxa at genus level in P_histicola mice.pdf", height = 4, width = 5)

```